// <auto-generated />
namespace ducktyper_home.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBodyToProjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBodyToProjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201605030852072_AddBodyToProjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
